/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Windows XP
 */
public class pin extends javax.swing.JFrame {

        int choice,z,pin=1234,counter=1,a=3;
        String Angka;
    /**
     * Creates new form pin
     */
    public pin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        login = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        ok = new javax.swing.JButton();
        ok1 = new javax.swing.JButton();
        ok2 = new javax.swing.JButton();
        ok3 = new javax.swing.JButton();
        ok4 = new javax.swing.JButton();
        ok5 = new javax.swing.JButton();
        ok6 = new javax.swing.JButton();
        ok7 = new javax.swing.JButton();
        ok8 = new javax.swing.JButton();
        ok9 = new javax.swing.JButton();
        ok10 = new javax.swing.JButton();
        ok11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Rage Italic", 1, 18)); // NOI18N
        jLabel1.setText("Selamat Datang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 10, 130, 50);

        jLabel2.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel2.setText("ANJUNGAN TUNAI MANDIRI");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 50, 270, 50);

        jLabel3.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel3.setText("BNI SYARIAH-BOJONEGORO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 100, 260, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Masukkan 6 digit pin Anda");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 160, 160, 30);

        login.setEditable(false);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(100, 200, 200, 30);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(null);

        ok.setText("RESET");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        jPanel1.add(ok);
        ok.setBounds(240, 430, 70, 40);

        ok1.setText("1");
        ok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok1ActionPerformed(evt);
            }
        });
        jPanel1.add(ok1);
        ok1.setBounds(80, 280, 70, 40);

        ok2.setText("2");
        ok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok2ActionPerformed(evt);
            }
        });
        jPanel1.add(ok2);
        ok2.setBounds(160, 280, 70, 40);

        ok3.setText("3");
        ok3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok3ActionPerformed(evt);
            }
        });
        jPanel1.add(ok3);
        ok3.setBounds(240, 280, 70, 40);

        ok4.setText("4");
        ok4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok4ActionPerformed(evt);
            }
        });
        jPanel1.add(ok4);
        ok4.setBounds(80, 330, 70, 40);

        ok5.setText("5");
        ok5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok5ActionPerformed(evt);
            }
        });
        jPanel1.add(ok5);
        ok5.setBounds(160, 330, 70, 40);

        ok6.setText("6");
        ok6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok6ActionPerformed(evt);
            }
        });
        jPanel1.add(ok6);
        ok6.setBounds(240, 330, 70, 40);

        ok7.setText("7");
        ok7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok7ActionPerformed(evt);
            }
        });
        jPanel1.add(ok7);
        ok7.setBounds(80, 380, 70, 40);

        ok8.setText("8");
        ok8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok8ActionPerformed(evt);
            }
        });
        jPanel1.add(ok8);
        ok8.setBounds(160, 380, 70, 40);

        ok9.setText("9");
        ok9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok9ActionPerformed(evt);
            }
        });
        jPanel1.add(ok9);
        ok9.setBounds(240, 380, 70, 40);

        ok10.setText("0");
        ok10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok10ActionPerformed(evt);
            }
        });
        jPanel1.add(ok10);
        ok10.setBounds(160, 430, 70, 40);

        ok11.setText("ENTER");
        ok11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok11ActionPerformed(evt);
            }
        });
        jPanel1.add(ok11);
        ok11.setBounds(80, 430, 70, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 540);

        setBounds(0, 0, 416, 578);
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed

    login.setText("");
         
                                          
      
// TODO add your handling code here:
    }//GEN-LAST:event_okActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void ok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok1ActionPerformed
        String ok1Text = login.getText() + ok1.getText();
        login.setText(ok1Text);
    }//GEN-LAST:event_ok1ActionPerformed

    private void ok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok2ActionPerformed
        // TODO add your handling code here:
        String ok2Text = login.getText() + ok2.getText();
        login.setText(ok2Text);
    }//GEN-LAST:event_ok2ActionPerformed

    private void ok3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok3ActionPerformed
        // TODO add your handling code here:
        String ok3Text = login.getText() + ok3.getText();
        login.setText(ok3Text);
    }//GEN-LAST:event_ok3ActionPerformed

    private void ok4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok4ActionPerformed
        // TODO add your handling code here:
        String ok4Text = login.getText() + ok4.getText();
        login.setText(ok4Text);
    }//GEN-LAST:event_ok4ActionPerformed

    private void ok5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok5ActionPerformed
        // TODO add your handling code here:
        String ok5Text = login.getText() + ok5.getText();
        login.setText(ok5Text);
    }//GEN-LAST:event_ok5ActionPerformed

    private void ok6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok6ActionPerformed
        // TODO add your handling code here:
        String ok6Text = login.getText() + ok6.getText();
        login.setText(ok6Text);
    }//GEN-LAST:event_ok6ActionPerformed

    private void ok7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok7ActionPerformed
        // TODO add your handling code here:
        String ok7Text = login.getText() + ok7.getText();
        login.setText(ok7Text);
    }//GEN-LAST:event_ok7ActionPerformed

    private void ok8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok8ActionPerformed
        // TODO add your handling code here:
        String ok8Text = login.getText() + ok8.getText();
        login.setText(ok8Text);
    }//GEN-LAST:event_ok8ActionPerformed

    private void ok9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok9ActionPerformed
        // TODO add your handling code here:
        String ok9Text = login.getText() + ok9.getText();
        login.setText(ok9Text);
    }//GEN-LAST:event_ok9ActionPerformed

    private void ok10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok10ActionPerformed
        // TODO add your handling code here:
        String ok10Text = login.getText() + ok10.getText();
        login.setText(ok10Text);
    }//GEN-LAST:event_ok10ActionPerformed

    private void ok11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok11ActionPerformed
        
        if(login.getText().trim().equals("110406")) {
            javax.swing.JOptionPane.showMessageDialog(null, "Selamat Datang");
            new Transaksi().setVisible(true);
            this.dispose();
        }
              
        else if (counter<3) { //jika pin salah
                                a--; //menghitung kesalahan login dan memberikan kesempatan login
                              javax.swing.JOptionPane.showMessageDialog(null,"Pin Salah!\nPastikan"
                                      + "PIN yang anda masukkan benar","ERROR",0);
                              javax.swing.JOptionPane.showMessageDialog(null,"\nKesempatan login " + 
                                      a + " kali lagi" + "\n");                         
                              
                              if (a==0) {
                                  System.exit(0);
                              }
                            }
    }//GEN-LAST:event_ok11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField login;
    private javax.swing.JButton ok;
    private javax.swing.JButton ok1;
    private javax.swing.JButton ok10;
    private javax.swing.JButton ok11;
    private javax.swing.JButton ok2;
    private javax.swing.JButton ok3;
    private javax.swing.JButton ok4;
    private javax.swing.JButton ok5;
    private javax.swing.JButton ok6;
    private javax.swing.JButton ok7;
    private javax.swing.JButton ok8;
    private javax.swing.JButton ok9;
    // End of variables declaration//GEN-END:variables
}
