/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Windows XP
 */
import javax.swing.JOptionPane;
import java.io.*;
        
public class Transaksi extends javax.swing.JFrame {

    /**
     * Creates new form Transaksi
     */
    String str1;
    int z,t,s,tab=50000;
    String Angka;
    public Transaksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ok1 = new javax.swing.JButton();
        ok2 = new javax.swing.JButton();
        ok3 = new javax.swing.JButton();
        ok4 = new javax.swing.JButton();
        ok5 = new javax.swing.JButton();
        ok6 = new javax.swing.JButton();
        ok7 = new javax.swing.JButton();
        ok8 = new javax.swing.JButton();
        ok9 = new javax.swing.JButton();
        ok11 = new javax.swing.JButton();
        ok10 = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        ok12 = new javax.swing.JButton();
        saldo = new javax.swing.JButton();
        penarikan = new javax.swing.JButton();
        penyetoran = new javax.swing.JButton();
        info = new javax.swing.JButton();
        nilai = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        ok1.setText("1");
        ok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok1ActionPerformed(evt);
            }
        });
        getContentPane().add(ok1);
        ok1.setBounds(70, 110, 70, 40);

        ok2.setText("2");
        ok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok2ActionPerformed(evt);
            }
        });
        getContentPane().add(ok2);
        ok2.setBounds(150, 110, 70, 40);

        ok3.setText("3");
        ok3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok3ActionPerformed(evt);
            }
        });
        getContentPane().add(ok3);
        ok3.setBounds(230, 110, 70, 40);

        ok4.setText("4");
        ok4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok4ActionPerformed(evt);
            }
        });
        getContentPane().add(ok4);
        ok4.setBounds(70, 160, 70, 40);

        ok5.setText("5");
        ok5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok5ActionPerformed(evt);
            }
        });
        getContentPane().add(ok5);
        ok5.setBounds(150, 160, 70, 40);

        ok6.setText("6");
        ok6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok6ActionPerformed(evt);
            }
        });
        getContentPane().add(ok6);
        ok6.setBounds(230, 160, 70, 40);

        ok7.setText("7");
        ok7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok7ActionPerformed(evt);
            }
        });
        getContentPane().add(ok7);
        ok7.setBounds(70, 210, 70, 40);

        ok8.setText("8");
        ok8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok8ActionPerformed(evt);
            }
        });
        getContentPane().add(ok8);
        ok8.setBounds(150, 210, 70, 40);

        ok9.setText("9");
        ok9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok9ActionPerformed(evt);
            }
        });
        getContentPane().add(ok9);
        ok9.setBounds(230, 210, 70, 40);

        ok11.setText("ENTER");
        ok11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok11ActionPerformed(evt);
            }
        });
        getContentPane().add(ok11);
        ok11.setBounds(70, 260, 70, 40);

        ok10.setText("0");
        ok10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok10ActionPerformed(evt);
            }
        });
        getContentPane().add(ok10);
        ok10.setBounds(150, 260, 70, 40);

        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(340, 270, 110, 30);

        ok12.setText("RESET");
        ok12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok12ActionPerformed(evt);
            }
        });
        getContentPane().add(ok12);
        ok12.setBounds(230, 260, 70, 40);

        saldo.setText("SALDO");
        saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoActionPerformed(evt);
            }
        });
        getContentPane().add(saldo);
        saldo.setBounds(340, 110, 110, 30);

        penarikan.setText("TARIK");
        penarikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penarikanActionPerformed(evt);
            }
        });
        getContentPane().add(penarikan);
        penarikan.setBounds(340, 150, 110, 30);

        penyetoran.setText("SETOR");
        penyetoran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penyetoranActionPerformed(evt);
            }
        });
        getContentPane().add(penyetoran);
        penyetoran.setBounds(340, 190, 110, 30);

        info.setText("INFO");
        info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoActionPerformed(evt);
            }
        });
        getContentPane().add(info);
        info.setBounds(340, 230, 110, 30);

        nilai.setEditable(false);
        nilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiActionPerformed(evt);
            }
        });
        getContentPane().add(nilai);
        nilai.setBounds(90, 40, 250, 30);

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 480, 320);

        setBounds(0, 0, 495, 359);
    }// </editor-fold>//GEN-END:initComponents

    private void ok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok1ActionPerformed
        String ok1Text = nilai.getText() + ok1.getText();
        nilai.setText(ok1Text);
        
    }//GEN-LAST:event_ok1ActionPerformed

    private void ok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok2ActionPerformed
        // TODO add your handling code here:
        String ok2Text = nilai.getText() + ok2.getText();
        nilai.setText(ok2Text);
    }//GEN-LAST:event_ok2ActionPerformed

    private void ok3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok3ActionPerformed
        // TODO add your handling code here:
        String ok3Text = nilai.getText() + ok3.getText();
        nilai.setText(ok3Text);
    }//GEN-LAST:event_ok3ActionPerformed

    private void ok4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok4ActionPerformed
        // TODO add your handling code here:
        String ok4Text = nilai.getText() + ok4.getText();
        nilai.setText(ok4Text);
    }//GEN-LAST:event_ok4ActionPerformed

    private void ok5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok5ActionPerformed
        // TODO add your handling code here:
        String ok5Text = nilai.getText() + ok5.getText();
        nilai.setText(ok5Text);
    }//GEN-LAST:event_ok5ActionPerformed

    private void ok6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok6ActionPerformed
        // TODO add your handling code here:
        String ok6Text = nilai.getText() + ok6.getText();
        nilai.setText(ok6Text);
    }//GEN-LAST:event_ok6ActionPerformed

    private void ok7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok7ActionPerformed
        // TODO add your handling code here:
        String ok7Text = nilai.getText() + ok7.getText();
        nilai.setText(ok7Text);
    }//GEN-LAST:event_ok7ActionPerformed

    private void ok8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok8ActionPerformed
        // TODO add your handling code here:
        String ok8Text = nilai.getText() + ok8.getText();
        nilai.setText(ok8Text);
    }//GEN-LAST:event_ok8ActionPerformed

    private void ok9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok9ActionPerformed
        // TODO add your handling code here:
        String ok9Text = nilai.getText() + ok9.getText();
        nilai.setText(ok9Text);
    }//GEN-LAST:event_ok9ActionPerformed

    private void ok11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ok11ActionPerformed

    private void ok10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok10ActionPerformed
        // TODO add your handling code here:
        String ok10Text = nilai.getText() + ok10.getText();
        nilai.setText(ok10Text);
    }//GEN-LAST:event_ok10ActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        z=JOptionPane.showConfirmDialog(null,"Apakah"
                + "Anda ingin keluar?","ATM BNI SYARIAH-BOJONEGORO",
                JOptionPane.YES_NO_OPTION, 3);
        if (z==1)
           new Transaksi().setVisible(true);
        else
            JOptionPane.showMessageDialog(null,"Terimakasih telah"
                    + "menggunakan ATM BNI SYARIAH - BOJONEGORO, ambil kartu ATM"
                    + "Anda.");
        System.exit(0);
        

        // TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    private void ok12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok12ActionPerformed
        // TODO add your handling code here:
        nilai.setText("");
    }//GEN-LAST:event_ok12ActionPerformed

    private void saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoActionPerformed

        nilai.setText(""+tab);        // TODO add your handling code here:
    }//GEN-LAST:event_saldoActionPerformed

    private void penarikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penarikanActionPerformed
        // TODO add your handling code here:
        str1 = nilai.getText();
        t = Integer.parseInt(str1);                                                                                                                
        tarik mengambil = new tarik();                                                                                                                
        mengambil.ambil(tab,t);                                                                                                                
        tab =mengambil.getsaldo();
        nilai.setText("");
    }//GEN-LAST:event_penarikanActionPerformed

    private void penyetoranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penyetoranActionPerformed
        // TODO add your handling code here:
        str1 = nilai.getText();
        s = Integer.parseInt(str1);
        setor hasil = new setor();
        hasil.menabung(tab, s);
        tab =hasil.getsaldo();
        nilai.setText("");
    }//GEN-LAST:event_penyetoranActionPerformed

    private void infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoActionPerformed
        
        new info().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_infoActionPerformed

    private void nilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nilaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton info;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField nilai;
    private javax.swing.JButton ok1;
    private javax.swing.JButton ok10;
    private javax.swing.JButton ok11;
    private javax.swing.JButton ok12;
    private javax.swing.JButton ok2;
    private javax.swing.JButton ok3;
    private javax.swing.JButton ok4;
    private javax.swing.JButton ok5;
    private javax.swing.JButton ok6;
    private javax.swing.JButton ok7;
    private javax.swing.JButton ok8;
    private javax.swing.JButton ok9;
    private javax.swing.JButton penarikan;
    private javax.swing.JButton penyetoran;
    private javax.swing.JButton saldo;
    // End of variables declaration//GEN-END:variables
}
